---
title: "Microbial speciation"
author: "Jay T. Lennon"
date: "`r format(Sys.time(), '%d %B, %Y')`"
header-includes:
  - \usepackage{array}
output: pdf_document
geometry: margin=2.54cm
---

# Setup Work Environment

```{r}
rm(list=ls())
getwd()
setwd("~/GitHub/MicroSpeciation/")

# Load packages
require("png")
require("grid")
````

# Load data
```{r}
data <- read.table("data/MicroSpeciation.txt", sep = "\t", header = T)
```

# Calculations
```{r}
# Use exponetial function Sf = S0.e^rt, where Sf = species richness at time final,
# So is speices richnness at time of origin which equals 1, r is the rate of 
# speciation, and t is the amount of time between origin and final

time <- data$Appeared - data$Extinction
rate <- (log(data$Richness/1)/time)
data <- data.frame(data, time, rate)
data <- data[order(rate),] 
micro <- data[ which(data$Taxon == 'Microbes'),]
micro.r <- micro[,6]

# How does speciation rate estimated from exponential model and 10^12 compare to 
# speciation rates estimate from the literature?

# Define a speciation event based on time it takes for 16S gene with length 1600 bp 
# to accumulate enough substitutions so gene is 3% divergent. 
# Number of substitutions needed is 1600 * 0.03 = 48
# Kuo and Ochman (2009) report substitution rates of 0.4 - 1.5 per million yrs.
# Corresponding times to divergence are 32 (48/1.5) to 120 (48/0.4) million yr. 
# With speciation rates of 0.008 (1/120) to 0.0313 (1/32) per million yr.
# Lower range is very close to estimates from the exponetial model = 0.007 per million yr.
# With low speciation estimate, plugged into exponential model = 7.8 * 10^13
Sf.low <- 1 * exp(0.008*4000)

# With high speciation estimate, plugged into exponential model = 2.4 * 10^54
Sf.high <- 1 * exp(0.0313*4000)

# What would substitution rate need to be to get 10^12 species? = 0.33
micro.r * 48

```

# Figure
```{r}
kern <- density(data$rate) 

png(filename="figures/speciation-kernel.png",
        width = 800, height = 800, res = 96*2)

par(mar = c(4, 5, 1, 1))  

plot(kern, main = NA, xaxt = "n", yaxt = "n", cex.lab = 1.5, ylab = "",
     xlab = "", xlim = c(-0.05, 0.16), ylim = c(0,12), lwd = 2)

mtext("Density", side = 2, outer = TRUE, cex = 1.5, 
      line = -2, adj = 0.5)

mtext(expression('Speciation Rate (mya'^-1*')'), side = 1, outer = TRUE, 
      cex = 1.5, line = -1, adj = 0.5)

     axis(side = 1, lwd.ticks = 2, cex.axis = 1.5, las = 1,
        at = c(-0.05, 0.0, 0.05, 0.10, 0.15), labels = T)

     axis(side = 3, lwd.ticks = 2, cex.axis = 1.5, las = 1,
        at = c(-0.05, 0.0, 0.05, 0.10, 0.15), labels = F)

     axis(side = 2, lwd.ticks = 2, cex.axis = 1.5, las = 1,
        at = c(0, 4, 8, 12), labels = T)

    axis(side = 4, lwd.ticks = 2, cex.axis = 1.5, las = 1,
        at = c(0, 4, 8, 12), labels = F)

box(lwd=2)

arrows(0.006907755, 4, 0.006907755, 7, length = 0.075, lwd = 2, col = "Black")
text(0.02, 3.5, labels = "microbes", cex = 1)

# Close Plot Device
dev.off()
graphics.off()

# Show Plot
img <- readPNG("figures/speciation-kernel.png")
grid.raster(img)
```
