---
title: "Microbial Speciation with Extinction"
author: "Ford Fishman"
date: "`r format(Sys.time(), '%d %B, %Y')`"
header-includes:
   - \usepackage{array}
output: pdf_document
geometry: margin=2.54cm
---

# Setup Work Environment

```{r}
rm(list=ls()) # removes all objects in the given environment
wd <- "~/Documents/LennonLab/GitHub/MicroSpeciation"
data_dir <- paste(wd, "/data/", sep = "")
figure_dir <- paste(wd, "/figures/", sep = "")
getwd()
setwd(wd)

# Load packages
require("png")
require("grid")
suppressPackageStartupMessages(library(kableExtra))
suppressPackageStartupMessages(library(tidyr))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(scales))
```

# Load data
```{r}
ext_file <- paste(data_dir, "Extinction_Rohde_Muller_raw.csv", sep = "")
ext <- read.csv(ext_file)

avg_ext <- c()

# Average out exitinction percentage over entire time period
for (i in 1:nrow(ext)){
  
  if (i == 1){

    era <- c(ext$ExtinctionIntensity[i])
    
  } else {
    
    if (ext$Diversity[i] == ext$Diversity[i-1] & ext$ExtinctionIntensity[i] == ext$ExtinctionIntensity[i-1]) {
      era <- c(era, ext$ExtinctionIntensity[i])
      if (i == nrow(ext)) {
        # integer(x) makes a vector of zeros of length x
        # the mean of extinction intensity is evenly distributed over an era's duration
        avg_ext <- c(avg_ext, integer(length(era)) + mean(era)/length(era))
      }
      
    } else {
      avg_ext <- c(avg_ext, integer(length(era)) + mean(era)/length(era))
      era <- c(ext$ExtinctionIntensity[i])
      if (i == nrow(ext)) {
        avg_ext <- c(avg_ext, integer(length(era)) + mean(era)/length(era))
      }
    }
  }
}

ext <- cbind(ext, AverageExtinction = avg_ext) 
ext$time <- as.character(4000 - ext$Mya)

names(avg_ext) <- ext$time
avg_ext <- avg_ext[order(names(avg_ext))] 
Ee <- c(integer(as.integer(names(avg_ext[1])) -1 ), avg_ext)/100
```

$$S_t = [S_{t-1} + S_{t-1}r(1 - \frac{S_{t-1}}{K})] * (1 - E_{e,t})$$
# Discrete logistic growth
```{r}
length.g <- 1600 # length of gene
cutoff <- 0.03 # % divergence for new OTU
subs = length.g * cutoff # number of substitutions needed for new OTU

# Speciation parameters
low.sub <- 0.4 # low end 16S substitution rate 
hi.sub <- 1.5 # High end 16S substitution rate

# set a range of speciation values in potential range
lambdas <- seq(low.sub, hi.sub, by = 0.01)/subs 

# set epsilon values
eps <- seq(0.1, 0.9, by = 0.01)

# extinction rates for each speciation value and epsilon value
mus <- data.frame(matrix(lambdas, ncol = 1) %*%  matrix(eps, nrow = 1))
colnames(mus) <- as.character(eps) # data frame of mu values per epsilon and lambda values

rs <- lambdas - mus
# Data frame to contain all parameter and simulation information

df <- cbind(
  SpeciationRate = rep(lambdas, length(mus)), # all lambda values
  gather(rs, key = epsilon, value = r, `0.1`:`0.9`)
)
df$epsilon <- as.double(df$epsilon)

K <- Inf # carrying capacity

Nfinal <- c() # estimate of current number of species 

for (i in 1:nrow(df)) {
  
  S <- 1 # initial number of species
  r <- df$r[i] # initial r for this iteration
  lambda <- df$SpeciationRate[i]
  # Extinction parameters
  ep <- df$epsilon[i]
  Eb <- rnorm(4000, mean = ep, sd = 0.05) # baseline epsilon
  Eb <- ifelse(Eb<0,0.01,Eb) # if Eb is ever less than 0, make it 0.1
  Eb <- ifelse(Eb>1,0.9,Eb)
  # Richness with discrete logistic with extinction
  for(time in 2:4000) {
    epsilon = Eb[time]
    mu <- lambda * epsilon 
    r <- lambda - mu # diversification rate update 
    S[time] = (S[time-1] + (S[time-1]*r) * (1-S[time-1]/K)) * (1 - Ee[time]) # growth
  }
  Nfinal <- c(Nfinal, S[4000])
  
}
df <- cbind(df, richness = Nfinal)

# Summary statistics
medians <- with(df, tapply(richness, epsilon, median))

# Plot
scatter_plot_file <- paste(figure_dir, "median-speciation_dynamic-eps_noGOE.png", sep = "")
png(filename = scatter_plot_file,
        width = 800, height = 800, res = 96*2)
par(mar = c(4, 5, 1, 1)) 

ggplot(NULL, aes(x = eps, y = medians)) + 
  geom_point(size = 0.3) + 
  # scale_y_log10(breaks = c(10^1, 10^6, 10^9, 10^12, 10^20)) + 
  scale_x_continuous("Epsilon", breaks = c(0.1, 0.3, 0.5, 0.7, 0.9)) +
  scale_y_log10("Expected Contemporary Richness", breaks = trans_breaks("log10", function(x) 10^x),
              labels = trans_format("log10", math_format(10^.x))) +
      theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        legend.position = "bottom",
        axis.line = element_line(colour = "black"))
  
# Close Plot Device
dev.off()
graphics.off()

# Show Plot
img <- readPNG(scatter_plot_file)
grid.raster(img)

# sum_stats_df <- cbind("0.1" = sum_stats$`0.1`, "0.5" = sum_stats$`0.5`, "0.9" = sum_stats$`0.9`)
# sum_stats_file <- paste(figure_dir, "dynamic-rates-no-GOE.html", sep = "")
# sum_stats_df %>%
#   kable() %>%
#   kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"), full_width = F) %>%
#   add_header_above(c(" ", "Epsilon" = 3)) %>% 
#   save_kable(file = sum_stats_file, self_contained = T)

# Ee <- ext$Ext[1:4000]/100 # mass extinction events sensu Sepkoski
# GOE <- rnorm(2426-2240, mean = 0.5, sd = 0.1) # great oxidation event
# GOE <- ifelse(GOE<0,0,GOE)
# # GOE <- ifelse(GOE>0.9, 0.9, GOE)
# GOE <- c(Ee[1:(4000-2426)],GOE,Ee[1761:4000])
# Ee <- GOE
# Eb.t <- 0.1 # initial Eb
# Ee.t <- 0.1 # initial Ee
# 
# 
# 
# # Number of taxa lost from baseline extinction
# for(time in 2:4000) {
#   Eb.t[time] = S[time-1] * Eb[time]
# }
# 
# # Number of taxa lost from mass extinction events
# for(time in 2:4000) {
#   Ee.t[time] = S[time-1] * Ee[time]
# }
# 
# # Dataframe with times, richness, and extinctioins
# E.total <- Eb.t + Ee.t
# # E.total <- Eb.t
# rich <- data.frame(1:4000, 4000:1, Eb, Ee, Ee+Eb, Eb.t, Ee.t, E.total, S)
# colnames(rich) <- c("time", "mya", "E.per.b", "E.per.e", "E.per.tot", "E.b.rich", "E.e.rich", "E.total.rich", "S")
```


