---
title: "Microbial Speciation with Extinction"
author: "Jay T. Lennon"
date: "`r format(Sys.time(), '%d %B, %Y')`"
header-includes:
   - \usepackage{array}
output: pdf_document
geometry: margin=2.54cm
---

# Setup Work Environment

```{r}
rm(list=ls())
getwd()
setwd("~/GitHub/MicroSpeciation/")

# Load packages
require("png")
require("grid")
````

# Load data
```{r}
ext <- read.table("~/GitHub/MicroSpeciation/data/Extinction_Rhode_Muller_2005.txt", sep = "\t", header = T)

ext[is.na(ext)] <- 0 # assign missing values a background extinction rate
```

# Discrete logistic growth
```{r}
r <- 0.0067 # speciation rate
S <- 1 # initial number of species
K <- Inf # carrying capacity
Eb <-0.1 # proportion of new species that go extinct per time step (i.e., "baseline extinction")
Ee <- ext$Ext[1:4000] # extinction events sensu Sepkoski
GOE <- rnorm(2426-2240, mean = 50, sd = 10)
GOE <- ifelse(GOE<0,0,GOE)
GOE <- ifelse(GOE>90, 90, GOE)
GOE <- c(Ee[1:(4000-2426)],GOE,Ee[2240:4000])
Ee <- GOE
Eb.t <- 0 # initial Eb
Ee.t <- 0 # initial Ee

# for(time in 2:4000) {
#   S[time] = S[time-1] + (S[time-1]*r) * (1-S[time-1]/K) # growth
#   - ((S[time-1]*r) * (1-S[time-1]/K) * Eb) # baseline extinction
#   - ((S[time-1]*r) * (1-S[time-1]/K) * Ee) # extinction events
# }

# Calculating richness with discrete logistic with extinction
for(time in 2:4000) {
  S[time] = S[time-1] + (S[time-1]*r) * (1-S[time-1]/K) # growth
  - (S[time-1] * Eb) # baseline extinction
  - (S[time-1] * Ee) # extinction events
}

# Calculating number of taxa lost from baseline extinction
for(time in 2:4000) {
  Eb.t[time] = S[time-1] * Eb
}

# Calculating number of taxa lost from extinction events
for(time in 2:4000) {
  Ee.t[time] = S[time-1] * Ee[time]
}

# Create dataframe with times and richness
E.total <- Eb.t + Ee.t
rich <- data.frame(ext$time[1:4000], ext$MYA[1:4000], S, Ee, Eb.t, Ee.t, E.total)
colnames(rich) <- c("time", "mya", "S", "E.per", "E.base", "E.event", "E.total" )
```

```{r}
png(filename="~/GitHub/MicroSpeciation/figures/logistic.richness.png",
        width = 800, height = 800, res = 96*2)

layout(matrix(c(1:3), byrow = T))
par(mar = c(0.5, 4, 1, 1), oma = c(3, 4, 1, 1))


plot(rich$mya, rich$S, type = "l", log = "xy", col = "red", xlim = c(max(rich$mya), min(rich$mya)), xlab = "Time (mya)", 
     las = 1, ylab = "Species Richness")

# Mass extinction
  # Great Oxidaton Event (http://www.pnas.org/content/114/8/1811)
rect(2426, min(rich$S), 2240, max(rich$S), 
     border = "gray", col = "gray")
  # Ordovician–Silurian transition
rect(450, min(rich$S), 440, max(rich$S), 
     border = "gray", col = "gray")
  # Late Devonian extinction
rect(375, min(rich$S), 360, max(rich$S), 
     border = "gray", col = "gray")
  # Permian–Triassic transition
rect(252, min(rich$S), 252, max(rich$S), 
     border = "gray", col = "gray")
  # Triassic-Jurassic extinction
rect(201.3, min(rich$S), 201.3, max(rich$S), 
     border = "gray", col = "gray")
  # Cretaceous-Paleogene
rect(66, min(rich$S), 66, max(rich$S), 
     border = "gray", col = "gray")

# Close Plot Device
dev.off()
graphics.off()

# Show Plot
img <- readPNG("~/GitHub/MicroSpeciation/figures/logistic.richness.png")
grid.raster(img)
```

# Discrete logistic growth
```{r}
log.growth <- function(R, S, K) {
	Snext <- R * S * (1-S/K) + S
	return(Snext)
}

# log.growth.ext <- function(R, S, K) {
# 	Snext <- (R*S*(1-S/K) + S) * E
# 	return(Snext)
# }

R <- 0.0067 # intrinsic growth rate
S <- ext$time # range of S corresponding to times
K <- 50 # carrying capacity
E <- ext$Ext # extinction events

St <- log.growth(R, S, K) #calculate S + 1 across ranage of S

# St.ext <- log.growth.ext(R, S, K, E) #calculate N+1 across ranage of N for Logistic

plot(ext$MYA, St, type = "l", col = "red", xlim = rev(range(ext$MYA)), xlab = "Time (mya)", 
     las = 1, ylab = "Species Richness")



N0 <- 1
K <-10^12
rmax <- 0.0067
C <- K/N0-1 
#first generate a list of time indices
t <- ext$time 
N <- K/(1+C*exp(-rmax*t))
#make it pretty
data.frame(t=t,N=N)
plot(t,N,type="l")

http://cnr.lwlss.net/DiscreteStochasticLogistic/
simDSLogistic=function(K,r,N0){
  # Unusually, for this model, we know the number of events a priori
  eventNo=K-N0
  # So we can just generate all required random numbers (quickly) in one go
  unifs=runif(eventNo)
  # Every event produces one cell and consumes one unit of nutrients
  clist=(N0+1):K
  # Simulate time between events by generating 
  # exponential random numbers using the inversion method
  dts=-log(1-unifs)/(r*clist*(1-clist/K))
  return(data.frame(t=c(0,cumsum(dts)),c=c(N0,clist)))
}



r <- 1.0067
S <- 1
K <- 10
for(time in 2:4000) {
  S[time]=S[time-1]*r
}

r <- 0.67
S <- 1
K <- 5

for(time in 2:40) {
  S[time] = S[time-1] + (S[time-1]*r) * (1-S[time-1]/K)
}

r <- 0.67
S <- 1
K <- 1000
Eb <- 0.1
Ee <- ext$Ext[2:40]

for(time in 2:40) {
  S[time] = S[time-1] + (S[time-1]*r) * (1-S[time-1]/K) # growth
  - ((S[time-1]*r) * (1-S[time-1]/K) * Eb) # baseline extinction
  - ((S[time-1]*r) * (1-S[time-1]/K) * Ee) # extinction events
}


```

